version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: faceapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: face_app
    depends_on:
      - db
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      DISPLAY: host.docker.internal:0.0

volumes:
  db_data:
